In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
with open("/content/shakespeare.txt","r",encoding="utf-8") as f:
    text = f.read()

In [5]:
type(text)

str

In [6]:
print(text[:1000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [7]:
len(text)

5445609

In [8]:
unique_char = set(text)
len(unique_char)

84

In [9]:
for pair in enumerate(unique_char):
    print(pair)

(0, '3')
(1, 's')
(2, 'V')
(3, 'Q')
(4, 'R')
(5, 'e')
(6, 'd')
(7, 'H')
(8, 'x')
(9, 'S')
(10, 'A')
(11, 'J')
(12, 'm')
(13, ',')
(14, 'P')
(15, 'p')
(16, 'I')
(17, ']')
(18, '9')
(19, ';')
(20, 'k')
(21, '1')
(22, '_')
(23, 't')
(24, '<')
(25, '(')
(26, 'E')
(27, 'T')
(28, 'u')
(29, 'w')
(30, 'a')
(31, 'M')
(32, ')')
(33, '2')
(34, 'q')
(35, 'o')
(36, 'B')
(37, '-')
(38, '8')
(39, '0')
(40, 'f')
(41, '4')
(42, '>')
(43, ' ')
(44, 'Y')
(45, '&')
(46, 'G')
(47, '6')
(48, 'K')
(49, '"')
(50, ':')
(51, '.')
(52, 'v')
(53, 'l')
(54, 'L')
(55, 'X')
(56, '5')
(57, '!')
(58, 'y')
(59, 'F')
(60, 'z')
(61, '7')
(62, 'Z')
(63, 'N')
(64, 'j')
(65, 'n')
(66, 'W')
(67, '`')
(68, "'")
(69, 'b')
(70, 'C')
(71, 'D')
(72, '\n')
(73, 'U')
(74, 'O')
(75, '|')
(76, '}')
(77, 'c')
(78, '?')
(79, '[')
(80, 'r')
(81, 'g')
(82, 'h')
(83, 'i')


In [10]:
# number -> letter
decoder = dict(enumerate(unique_char))

In [11]:
# letter -> number
encoder = {v: k for k,v in decoder.items()}
encoder

{'3': 0,
 's': 1,
 'V': 2,
 'Q': 3,
 'R': 4,
 'e': 5,
 'd': 6,
 'H': 7,
 'x': 8,
 'S': 9,
 'A': 10,
 'J': 11,
 'm': 12,
 ',': 13,
 'P': 14,
 'p': 15,
 'I': 16,
 ']': 17,
 '9': 18,
 ';': 19,
 'k': 20,
 '1': 21,
 '_': 22,
 't': 23,
 '<': 24,
 '(': 25,
 'E': 26,
 'T': 27,
 'u': 28,
 'w': 29,
 'a': 30,
 'M': 31,
 ')': 32,
 '2': 33,
 'q': 34,
 'o': 35,
 'B': 36,
 '-': 37,
 '8': 38,
 '0': 39,
 'f': 40,
 '4': 41,
 '>': 42,
 ' ': 43,
 'Y': 44,
 '&': 45,
 'G': 46,
 '6': 47,
 'K': 48,
 '"': 49,
 ':': 50,
 '.': 51,
 'v': 52,
 'l': 53,
 'L': 54,
 'X': 55,
 '5': 56,
 '!': 57,
 'y': 58,
 'F': 59,
 'z': 60,
 '7': 61,
 'Z': 62,
 'N': 63,
 'j': 64,
 'n': 65,
 'W': 66,
 '`': 67,
 "'": 68,
 'b': 69,
 'C': 70,
 'D': 71,
 '\n': 72,
 'U': 73,
 'O': 74,
 '|': 75,
 '}': 76,
 'c': 77,
 '?': 78,
 '[': 79,
 'r': 80,
 'g': 81,
 'h': 82,
 'i': 83}

In [12]:
encoded_text = np.array([encoder[char] for char in text])
encoded_text

array([72, 43, 43, ..., 26, 63, 71])

In [13]:
encoded_text[:500]

array([72, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43,
       43, 43, 43, 43, 43, 21, 72, 43, 43, 59, 80, 35, 12, 43, 40, 30, 83,
       80,  5,  1, 23, 43, 77, 80,  5, 30, 23, 28, 80,  5,  1, 43, 29,  5,
       43,  6,  5,  1, 83, 80,  5, 43, 83, 65, 77, 80,  5, 30,  1,  5, 13,
       72, 43, 43, 27, 82, 30, 23, 43, 23, 82,  5, 80,  5, 69, 58, 43, 69,
        5, 30, 28, 23, 58, 68,  1, 43, 80, 35,  1,  5, 43, 12, 83, 81, 82,
       23, 43, 65,  5, 52,  5, 80, 43,  6, 83,  5, 13, 72, 43, 43, 36, 28,
       23, 43, 30,  1, 43, 23, 82,  5, 43, 80, 83, 15,  5, 80, 43,  1, 82,
       35, 28, 53,  6, 43, 69, 58, 43, 23, 83, 12,  5, 43,  6,  5, 77,  5,
       30,  1,  5, 13, 72, 43, 43,  7, 83,  1, 43, 23,  5, 65,  6,  5, 80,
       43, 82,  5, 83, 80, 43, 12, 83, 81, 82, 23, 43, 69,  5, 30, 80, 43,
       82, 83,  1, 43, 12,  5, 12, 35, 80, 58, 50, 72, 43, 43, 36, 28, 23,
       43, 23, 82, 35, 28, 43, 77, 35, 65, 23, 80, 30, 77, 23,  5,  6, 43,
       23, 35, 43, 23, 82

In [14]:
decoder[6]

'd'

In [15]:
def one_hot_encode(encoded_text,num_unique_char):
    one_hot = np.zeros((encoded_text.size,num_unique_char))
    # Convert to float32 datatype for PyTorch usage later on
    one_hot = one_hot.astype(np.float32)
    one_hot[np.arange(one_hot.shape[0]),encoded_text.flatten()] = 1.0
    one_hot = one_hot.reshape((*encoded_text.shape,num_unique_char))
    return one_hot

In [16]:
arr = np.array([1,2,0])
arr

array([1, 2, 0])

In [17]:
one_hot_encode(arr,3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [18]:
def generate_batches(encoded_text,samples_per_batch=10,sequence_length=50):
    # X -> encoded text of length sequence length
    # [0,1,2]
    # [1,2,3]
    # Y -> encoded text shifted by 1
    # [1,2,3]
    # [2,3,4]
    # number of characters in each batch
    char_per_batch = samples_per_batch * sequence_length
    # number of batches given the length of encoded text
    num_batches = len(encoded_text) // char_per_batch
    # Cut off the end of the encoded text which won't fit into a batch
    encoded_text = encoded_text[:num_batches*char_per_batch]
    encoded_text = encoded_text.reshape((samples_per_batch,-1))

    for n in range(0,encoded_text.shape[1],sequence_length):
        x = encoded_text[:,n:n+sequence_length]
        y = np.zeros_like(x)

        try:
            y[:,:-1] = x[:,1:]
            y[:,-1] = encoded_text[:,n+sequence_length]
        except:
            y[:,:-1] = x[:,1:]
            y[:,-1] = encoded_text[:,0]

        yield x, y

In [19]:
sample_text = np.arange(24)
sample_text

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
batch_generator = generate_batches(sample_text,samples_per_batch=2,sequence_length=5)

In [21]:
x, y = next(batch_generator)

In [22]:
x

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [23]:
y

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [32]:
class LSTM(nn.Module):

    def __init__(self,unique_char,hidden_units=256,num_layers=5,dropout_probability=0.5,use_gpu=False):
        super().__init__()
        self.hidden_units = hidden_units
        self.num_layers = num_layers
        self.dropout_prob = dropout_probability
        self.unique_char = unique_char
        self.use_gpu = use_gpu
        self.decoder = dict(enumerate(unique_char))
        self.encoder = {idx: char for char, idx in self.decoder.items()}
        self.lstm = nn.LSTM(len(self.unique_char),hidden_units,num_layers,dropout=dropout_probability,batch_first=True)
        self.dropout = nn.Dropout(self.dropout_prob)
        self.linear = nn.Linear(self.hidden_units,len(self.unique_char))

    def forward(self,seq,hidden):
        lstm_output, hidden = self.lstm(seq,hidden)
        dropout_output = self.dropout(lstm_output)
        dropout_output = dropout_output.contiguous().view((-1,self.hidden_units))
        final_output = self.linear(dropout_output)
        return final_output, hidden

    def hidden_state(self,batch_size):
        if self.use_gpu:
            return (torch.zeros(self.num_layers,batch_size,self.hidden_units).cuda(),torch.zeros(self.num_layers,batch_size,self.hidden_units).cuda())
        else:
            return (torch.zeros(self.num_layers,batch_size,self.hidden_units),torch.zeros(self.num_layers,batch_size,self.hidden_units))

In [33]:
torch.manual_seed(42)

model = LSTM(unique_char,hidden_units=512,num_layers=3,dropout_probability=0.5,use_gpu=True)
model

LSTM(
  (lstm): LSTM(84, 512, num_layers=3, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5, inplace=False)
  (linear): Linear(in_features=512, out_features=84, bias=True)
)

In [34]:
total_params = 0

for param in model.parameters():
    total_params += param.numel()

print("Total parameters:", total_params)

Total parameters: 5470292


In [35]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)

In [36]:
train_percent = 0.9
train_idx = int(len(encoded_text)*train_percent)

train_data = encoded_text[:train_idx]
test_data = encoded_text[train_idx:]

In [38]:
epochs = 20
batch_size = 100
sequence_len = 100
tracker = 0
num_char = max(encoded_text)+1

model.train()

if model.use_gpu:
    model.cuda()

for i in range(epochs):
    hidden_state = model.hidden_state(batch_size)

    for x, y in generate_batches(train_data,batch_size,sequence_len):
        tracker += 1
        x = one_hot_encode(x,num_char)

        inputs = torch.from_numpy(x)
        outputs = torch.from_numpy(y)

        if model.use_gpu:
            inputs = inputs.cuda()
            outputs = outputs.cuda()

        hidden_state = tuple([state.data for state in hidden_state])
        model.zero_grad()

        lstm_output, hidden_state = model.forward(inputs,hidden_state)
        loss = criterion(lstm_output,outputs.view(batch_size*sequence_len).long())
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(),max_norm=5)
        optimizer.step()

        if tracker % 25 == 0:
            val_hidden_state = model.hidden_state(batch_size)
            val_losses = []
            model.eval()

            for x, y in generate_batches(test_data,batch_size,sequence_len):
                x = one_hot_encode(x,num_char)

                inputs = torch.from_numpy(x)
                outputs = torch.from_numpy(y)

                if model.use_gpu:
                    inputs = inputs.cuda()
                    outputs = outputs.cuda()

                val_hidden_state = tuple([state.data for state in val_hidden_state])

                lstm_output, val_hidden_state = model.forward(inputs,val_hidden_state)
                val_loss = criterion(lstm_output,outputs.view(batch_size*sequence_len).long())
                val_losses.append(val_loss.item())

            model.train()

            print(f"Epoch {i+1} Step {tracker} Validation Loss: {val_loss.item()}")

Epoch 1 Step 25 Validation Loss: 3.19205379486084
Epoch 1 Step 50 Validation Loss: 3.179020404815674
Epoch 1 Step 75 Validation Loss: 3.059781074523926
Epoch 1 Step 100 Validation Loss: 2.9559810161590576
Epoch 1 Step 125 Validation Loss: 2.8413662910461426
Epoch 1 Step 150 Validation Loss: 2.716247081756592
Epoch 1 Step 175 Validation Loss: 2.63789439201355
Epoch 1 Step 200 Validation Loss: 2.545100450515747
Epoch 1 Step 225 Validation Loss: 2.4303112030029297
Epoch 1 Step 250 Validation Loss: 2.340391159057617
Epoch 1 Step 275 Validation Loss: 2.2656970024108887
Epoch 1 Step 300 Validation Loss: 2.194387197494507
Epoch 1 Step 325 Validation Loss: 2.145447015762329
Epoch 1 Step 350 Validation Loss: 2.0970492362976074
Epoch 1 Step 375 Validation Loss: 2.060091257095337
Epoch 1 Step 400 Validation Loss: 2.028076648712158
Epoch 1 Step 425 Validation Loss: 1.9985202550888062
Epoch 1 Step 450 Validation Loss: 1.9719905853271484
Epoch 1 Step 475 Validation Loss: 1.9422369003295898
Epoch 2 S

In [39]:
torch.save(model.state_dict(),"shakespeare_text_generator.net")

In [40]:
def predict_next_char(model,char,hidden_state=None,k=1):
    encoded_text = model.encoder[char]
    encoded_text = np.array([[encoded_text]])
    encoded_text = one_hot_encode(encoded_text,len(model.unique_char))
    encoded_text = torch.from_numpy(encoded_text)

    if model.use_gpu:
      encoded_text = encoded_text.cuda()

    hidden_state = tuple([state.data for state in hidden_state])
    lstm_output, hidden_state = model.forward(encoded_text,hidden_state)
    probs = F.softmax(lstm_output,dim=1).data # Raw probabilities for every single character

    if model.use_gpu:
        probs = probs.cpu() # Use probabilities with Numpy to get top K probabilities

    probs, index_positions = probs.topk(k) # Returns how many characters to consider in our probabilities choice
    index_positions = index_positions.numpy().squeeze() # Put it back into the CPU and get it into the right shape
    probs = probs.numpy().flatten() # Convert to probabilities per index
    probs = probs/probs.sum()
    char = np.random.choice(index_positions,p=probs)
    return model.decoder[char], hidden_state

In [42]:
def generate_text(model,size,seed="The",k=1):
    if model.use_gpu:
      model.cuda()

    model.eval()
    output_chars = [char for char in seed]
    hidden_state = model.hidden_state(1)

    for char in seed:
      char, hidden_state = predict_next_char(model,char,hidden_state,k)

    output_chars.append(char)

    for i in range(size):
      char, hidden_state = predict_next_char(model,output_chars[-1],hidden_state,k)
      output_chars.append(char)

    return "".join(output_chars)

In [44]:
print(generate_text(model,size=1000,seed="The ",k=3))

The states.

                              Enter CLARENCE

    There's a service to you.
  CASSIUS. I will be so so so much and shed.
    I will not strike the will and more than she.
    I would not be a most assurance to my son.
    If they should spend myself it were a strange,
    Whose such an angel to an angel show
    With such a man off as I will not stay,
    And we are all the matter of his fair
    To merciless the state. I seek more son
    The strong of men that the with this distain  
    With the secret of my soldiers that the most  
    They say I shall stay where you are a serving
    And she it was the sun and men of heaven,
    With strength to she with me and wear the war.
    I would not set them well. Then I have strong,
    To tell you, and I'll tell you that I have
    I should be sent to th' traitor. Thou shalt not be.
    I will not see the common thoughts of her
    That the most soul of men's dear singer thought
    That sent his heart as words, and which in